
cc = gcc
prog = bitree 
source = bitree.c bitree_test.c ../02-stack/stack.c ../02-stack/stack.h ../00-list/list.c ../00-list/list.h ../03-queue/queue.c ../03-queue/queue.h

$(prog):$(source)
	$(cc) -g -o $(prog) $(source)

clean:
	rm bitree 
